### ISSUE TITLE
About zk_ecrecover

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-rom#107]
I read [usage-ecrecover.md](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/docs/usage-ecrecover.md), is [https://github.com/hermeznetwork/zk_ecrecover](https://github.com/hermeznetwork/zk_ecrecover) not available yet?

**Comment by krlosMata** [comment]
> I read [usage-ecrecover.md](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/docs/usage-ecrecover.md), is https://github.com/hermeznetwork/zk_ecrecover not available yet?

- `zk_ecrecover` has been moved inside the `zkevm-rom` repository
- You can find the same source code as [zk_ecrecover](https://github.com/hermeznetwork/zk_ecrecover) in https://github.com/0xPolygonHermez/zkevm-rom/tree/main/main/ecrecover

**Comment by 3for** [comment]
Thanks @krlosMata
