### ISSUE TITLE
Unnecessary code in process-tx.zkasm?

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-rom#136]
In [https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm#L130](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm#L130):
```
        HASHPOS => D
        1 => D
```
set D register twice, actually the D value 1 is used, so do we can remove `HASHPOS => D` here?

**Comment by krlosMata** [comment]
you are right !!
Thanks for noticing it.
We will remove the unnecessary line in the coming days
