### ISSUE TITLE
tx RLP `value0` typo?

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-rom#213]
[https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/load-tx-rlp.zkasm#L171](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/load-tx-rlp.zkasm#L171):
```
value0:
        0 => A
                                        :JMPN(endValue)
```
should be changed to:
```
value0:
        0 => A
                                        :JMP(endValue)
```
Or it will still go into the "shortValue" branch.

**Comment by ignasirv** [comment]
Yes you are right, nice catch, thank you!
