### ISSUE TITLE
Why not change the chainID max size from 64 bit to 256 bit?

### ISSUE THREAD

**Issue by 3for** [0xPolygonHermez/zkevm-rom#274]
In [Hexens audit report](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/audits/Hexens_Polygon_zkEVM_PUBLIC_27.02.23.pdf) , the 8-th weakness, said: 
EVM chainID max size is 256 bit

But our [chainID](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/load-tx-rlp.zkasm#L224) max size is still 64 bit.
I want to learn the reason about why not fix this mismatch?

**Comment by krlosMata** [comment]
Sure !!
There are several reasons:
- `chainID` is forwarded from smart contracts to the ROM as it is a part of the SNARK input. It is defined there to be `uint64` so in the ROM we must assume that it is the same as the smart contract. Shorter bytes to add to the inputs means less contratints in the circuit
- also `chainID` is mapped to the register `GAS` at the very first ROM execution. `GAS` is one field element which is almost 64 bits

**Comment by 3for** [comment]
Thanks @krlosMata
