### ISSUE TITLE
How to guarantee the correctness of the GlobaExitRoot when setting its value in Global_exit_root_manager_l2 contract?

### ISSUE THREAD

**Issue by Federico2014** [0xPolygonHermez/zkevm-rom#284]
How to guarantee the correctness of the `GlobaExitRoot` when setting its value in `Global_exit_root_manager_l2` contract?
```
setGlobalExitRoot:
        0 => HASHPOS
        $ => E                                  :MLOAD(lastHashKIdUsed)
        E+1 => E                                :MSTORE(lastHashKIdUsed)

        32 => D
        A                                       :HASHK(E)
        %GLOBAL_EXIT_ROOT_STORAGE_POS           :HASHK(E) ; Storage position of the global exit root map
        HASHPOS                                 :HASHKLEN(E)
        $ => C                                  :HASHKDIGEST(E)

        %ADDRESS_GLOBAL_EXIT_ROOT_MANAGER_L2 => A
        %SMT_KEY_SC_STORAGE => B

        ; read timestamp given the globalExitRoot
        ; skip overwrite timestamp if it is different than 0
        ; Since timestamp is enforced by the smart contract it is safe to compare only 32 bits in 'op0' with JMPNZ
        $ => D                                  :SLOAD, JMPNZ(skipSetGlobalExitRoot)

        $ => D                                  :MLOAD(timestamp)
        $ => SR                                 :SSTORE ; Store 'timestamp' in storage position 'keccak256(globalExitRoot, 0)'
```

I mean what if the sequencer set the fake `GlobaExitRoot` instead of the one reading from L1  `globalexitrootmanager`contract,  there is no way to check it. If it succeeds, then someone may claim the assets of the leaf node that actually doesn't exist from the L2 bridge.

**Comment by krlosMata** [comment]
`globaExitRoot` is loaded as a free input [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/main.zkasm#L27) and it is loaded in the `PolygonZkEVMGlobalExitRootL2`. Then, it is hashed in the [`newAccInputHash`](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/main.zkasm#L166) among other fields.

Note that [`newAccInputHash`](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/main.zkasm#L197) is an output of the batch processing and it must match with the one computed by the [smart contract in L1](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVM.sol#L573) and the `globalExitRoot` provided by the sequencer [must exist](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVM.sol#L544).

The `accInputHash` is part of the [verifier public input](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVM.sol#L1662)

**Comment by Federico2014** [comment]
> `globaExitRoot` is loaded as a free input [here](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/main.zkasm#L27) and it is loaded in the `PolygonZkEVMGlobalExitRootL2`. Then, it is hashed in the [`newAccInputHash`](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/main.zkasm#L166) among other fields.
> 
> Note that [`newAccInputHash`](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/main.zkasm#L197) is an output of the batch processing and it must match with the one computed by the [smart contract in L1](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVM.sol#L573) and the `globalExitRoot` provided by the sequencer [must exist](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVM.sol#L544).
> 
> The `accInputHash` is part of the [verifier public input](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/PolygonZkEVM.sol#L1662)

Thank you so much for your reply, this is quite a sophisticated design, I get it.
