### ISSUE TITLE
[Bug]: Cold address access should not be rolled back in contract creation

### ISSUE THREAD

**Issue by last-las** [0xPolygonHermez/zkevm-rom#389]
### Version

367e31c3bb9f45e1fd606c16821ca637281c5861

### Description

According to [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929), even if a `CREATE` / `CREATE2` operation fails, the calculated destination address should remain in `access_addresses` (the warm address set).

However zkevm-rom reverts this change by setting the value of `touchedSR` to `initTouchedSR`.

### Steps to reproduce

An example case to trigger this issue could be: 

During a transaction, the contract first tries to create an existing contract using `CREATE2`, and then makes a `CALL` to this contract. The `CREATE2` operation should fail, but the contract address should remain in the `access_addresses`. Due to zkevm-rom reverts this change, the `COLD_ACCOUNT_ACCESS_COST` is deduced again from the caller during the `CALL` (the first one is deduced during the `CREATE2` operation), which is incorrect.

### The related code

**zkevm-rom**
zkevm-rom invokes `isColdAddress` to add the new calculated address to touched addresses: https://github.com/0xPolygonHermez/zkevm-rom/blob/367e31c3bb9f45e1fd606c16821ca637281c5861/main/process-tx.zkasm#L332

During `isColdAddress`, the address is set to warm and `touchedSR` is changed: https://github.com/0xPolygonHermez/zkevm-rom/blob/367e31c3bb9f45e1fd606c16821ca637281c5861/main/touched.zkasm#L104-L112

When the address collides, `deployAddresscollision` routine is invoked: https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/process-tx.zkasm#L341

During `deployAddresscollision`, `revertTouched` is invoked and `touchedSR` is revert: https://github.com/0xPolygonHermez/zkevm-rom/blob/367e31c3bb9f45e1fd606c16821ca637281c5861/main/touched.zkasm#L16-L18

**go-ethereum**
In go-ethereum, the access-list change is not rolled back even if the creation fails. 

https://github.com/ethereum/go-ethereum/blob/44a50c9f96386f44a8682d51cf7500044f6cbaea/core/vm/evm.go#L457-L461

**Comment by ignasirv** [comment]
Hi @last-las ,
Your bug has been confirmed as a completeness issue. I have create a PR with the fix and it will be applied for the next release.
Test with the error -> https://github.com/0xPolygonHermez/zkevm-testvectors/pull/253
Proposal fix at ROM -> https://github.com/0xPolygonHermez/zkevm-rom/pull/390

Thanks for the issue, amazing finding ^^
