### ISSUE TITLE
[Question]: Does 0x5 modexp work now?

### ISSUE THREAD

**Issue by doutv** [0xPolygonHermez/zkevm-rom#405]
### Version

Etrog

### Description

 > While the testnet for the Etrog upgrade supported five additional precompiles, modexp will be disabled on mainnet and testnet due to an edge case that arose in testing.
Source: https://polygon.technology/blog/polygon-zkevm-the-etrog-upgrade-is-live-on-mainnet

**Comment by krlosMata** [comment]
It does not in fork.11 version and previous ones (fork.8-9-10):
- fork.11 --> https://github.com/0xPolygonHermez/zkevm-rom/blob/v7.0.0-fork.11/main/precompiled/selector.zkasm#L73

**Comment by doutv** [comment]
Why modexp is disabled? could you provide more details? @krlosMata
